StylesPath = .vale/styles
MinAlertLevel = suggestion
Packages = Microsoft, write-good, alex, Joblint
Vocab = zoidberg

[*]
BasedOnStyles = Vale, Microsoft, write-good, alex
TokenIgnores = (?i)\b(?:Astro|ENTER)\b, \b[a-z]+(?:_[a-z0-9]+)+\b
BlockIgnores = (?s)<script\b[^>]*>.*?</script>

# Useful
Vale.Spelling = YES
Vale.Terms = YES
Vale.Repetition = YES
Microsoft.Headings = NO
Microsoft.HeadingAcronyms = NO
Microsoft.Acronyms = NO
Microsoft.FirstPerson = NO
Microsoft.We = NO
Microsoft.Semicolon = NO
Microsoft.Passive = NO
alex.ProfanityUnlikely = NO
write-good.E-Prime = NO

# So it doesn't become obnoxious
write-good.Passive = NO
write-good.TooWordy = suggestion
write-good.Weasel = warning

[dist/profile/**]
BasedOnStyles = Vale, Microsoft, write-good, alex, Joblint

[dist/artifacts/dotfiles/**]
Microsoft.Terms = NO
