StylesPath = .vale/styles
MinAlertLevel = suggestion
Packages = Microsoft, write-good, alex, Joblint
Vocab = zoidberg

[*]
BasedOnStyles = Vale, Microsoft, write-good, alex, Joblint
TokenIgnores = (?i)\b(?:Astro|ENTER)\b, \b[a-z]+(?:_[a-z0-9]+)+\b

# Useful
Vale.Spelling = YES
Vale.Terms = YES
Vale.Repetition = YES
Microsoft.Headings = NO
Microsoft.Acronyms = NO

# So it doesn't become obnoxious
write-good.Passive = warning
write-good.TooWordy = suggestion
write-good.Weasel = warning
